config/routes.rb
Rails.application.routes.draw do
  root "friends#index"
  resources :friends do
    resources :gifts, only: [:create, :edit, :update, :destroy, :show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  has_many :gifts, dependent: :destroy, inverse_of: :friend
  accepts_nested_attributes_for  :gifts, allow_destroy: true, reject_if: :all_blank


  # Add validations for presence of name and birthday
  validates :name, presence: true
  validates :birthday, presence: true
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :friend

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :link, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
    @friend.gifts.build
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
    @friend.gifts.build if @friend.gifts.empty?
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :birthday, gifts_attributes: [:id, :name, :price, :link, :_destroy])
    end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_friend
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  def index
    @gifts = Gift.all
  end

  def new
    @gift = Gift.new
  end
  def show
    @gift
  end

  def create
    @gift = @friend.gifts.build(gift_params)

    if @gift.save
      respond_to do |format|
        format.turbo_stream { render 'gifts/turbo_stream' }
        format.html { redirect_to @friend, notice: 'Gift was successfully created.' }
      end
    else
      respond_to do |format|
        format.turbo_stream { render 'gifts/turbo_stream', status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    unless @gift
      respond_to do |format|
        format.turbo_stream { render 'gifts/turbo_stream', status: :not_found }
        format.html { redirect_to @friend, alert: 'Gift not found.' }
      end
    end
  end


  def update
    if @gift.update(gift_params)
      respond_to do |format|
        format.turbo_stream { render 'gifts/turbo_stream' }
        format.html { redirect_to @friend, notice: 'Gift was successfully updated.' }
      end
    else
      respond_to do |format|
        format.turbo_stream { render 'gifts/turbo_stream', status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gift.destroy
    respond_to do |format|
      format.turbo_stream { render 'gifts/turbo_stream' }
      format.html { redirect_to @friend, notice: 'Gift was successfully destroyed.' }
    end
  end

  private

  def set_friend
    @friend = Friend.find(params[:friend_id])
  end

  def set_gift
    @gift = @friend.gifts.find_by(id: params[:id])
    if @gift.nil?
      redirect_to friend_path(@friend), alert: "Gift not found."
    end
  end

  def gift_params
    params.require(:gift).permit(:name, :price, :link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, data:
  { controller: 'nested-form', nested_form_wrapper_selector_value:
    '.nested-form-wrapper' }) do |form| %>

  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <%= form.label :name, 'Name', class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control', required: true, placeholder: 'First name' %>
    </div>
    <div class="col-md-6">
      <%= form.label :birthday, 'Birthday', class: 'form-label' %>
      <%= form.date_field :birthday, class: 'form-control', start_year: 1900, end_year: Time.now.year, placeholder: 'Birthday' %>
    </div>
  </div>

  <h3>Gifts</h3>

  <template data-nested-form-target="template">
    <%= form.fields_for :gifts, Gift.new, child_index: 'NEW_RECORD' do |gift_fields| %>
      <%= render "friends/gift_fields", f: gift_fields %>
    <% end %>
  </template>

  <%= form.fields_for :gifts do |gift_fields| %>
    <%= render "friends/gift_fields", f: gift_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <br>

  <button type="button" data-action="nested-form#add" class="btn btn-info">Add Gift</button>

  <div>
    <%= form.submit 'Save', class: 'btn btn-primary mt-3' %>
  </div>

<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Name:</strong>
    <%= friend.name %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= friend.birthday %>
  </p>

</div>

app/views/friends/_gift_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="row">
    <div class="col">
      <%= f.label :name, 'Description', class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>
    <div class="col">
      <%= f.label :price, 'Price', class: 'form-label' %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>
    <div class="col">
      <%= f.label :link, 'Link', class: 'form-label' %>
      <%= f.text_field :link, class: 'form-control' %>
    </div>
    <div class="col-auto d-flex align-items-end">
      <button type="button" data-action="nested-form#remove">Remove Gift</button>
      <%= f.hidden_field :_destroy %>
    </div>
  </div>
</div>

app/views/friends/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Friends List', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- Link to add a new friend -->
        <li class="nav-item">
          <%= link_to "Add Friends", new_friend_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/friends/edit.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">Edit Friend</h1>
      <%= render 'form', friend: @friend %>

      <div class="mt-4">
        <%= link_to "Show this friend", @friend, class: 'btn btn-secondary' %>
        <%= link_to "Back to friends", friends_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/friends/index.html.erb
<div class="container">
  <h1>Friends List</h1>
  <table class="table table-bordered table-striped table-hover">
    <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Birthday</th>
      <th colspan="2">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= link_to friend.name, friend %></td>
        <td><%= friend.birthday %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend), class: 'btn btn-outline-secondary' %></td>
        <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'New Friend', new_friend_path, class: 'btn btn-primary' %>
</div>

app/views/friends/new.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title">New Friend</h1>
      <%= render 'form', friend: @friend %>

      <div class="mt-4">
        <%= link_to "Back to friends", friends_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="container-fluid py-5">
  <div class="h-100 p-5 text-bg-light rounded-3">
    <h1 class="display-5 fw-bold"><%= @friend.name %></h1>
    <p style="color: green"><%= notice %></p>

    <div class="mt-4">
      <table class="table table-bordered table-striped table-hover">
        <thead class="table-dark">
        <tr>
          <th>Attribute</th>
          <th>Details</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>Birthday</td>
          <td><%= @friend.birthday %></td>
        </tr>
        </tbody>
      </table>

      <h3 class="mt-4">Gifts</h3>
      <table class="table table-bordered table-striped table-hover">
        <thead class="table-dark">
        <tr>
          <th>Gift Name</th>
          <th>Gift Price</th>
          <th>Gift Link</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @friend.gifts.each do |gift| %>
          <tr id="<%= dom_id(gift) %>">
            <td><%= gift.name %></td>
            <td><%= number_to_currency(gift.price) %></td>
            <td><%= link_to 'Link', gift.link, target: '_blank' %></td>
            <td>
              <%= link_to 'Edit', edit_friend_gift_path(gift.friend, gift), class: 'btn btn-secondary btn-sm' %>
              <%= link_to 'Destroy', friend_gift_path(gift.friend, gift), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <h3 class="mt-4"> Add a New Gift </h3>

      <%= render "form", friend: @friend %>

      <div class="mt-4">
        <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-outline-secondary" %>
        <%= link_to "Back to friends", friends_path, class: "btn btn-outline-secondary" %>
        <%= button_to "Remove Friend", @friend, method: :delete, data: { confirm: 'Are you sure you want to delete this friend?' }, class: "btn btn-outline-danger" %>
      </div>
    </div>
  </div>
</div>

<%= turbo_stream_from @friend %>

app/views/gifts/_form.html.erb
<%= form_with(model: [friend, gift], local: false, data:
  { controller: 'nested-form',
    nested_form_wrapper_selector_value: '.nested-form-wrapper'
  }) do |form| %>
  <% if gift.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(gift.errors.count, "error") %> prohibited this gift from being saved:</h4>
      <ul>
        <% gift.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Name', class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price, class: 'form-label' %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :link, class: 'form-label' %>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit 'Save', class: 'btn btn-primary mt-3' %>
  </div>

  <template data-gifts-target="template">
    <div class="nested-fields" data-new-record="true">
      <div class="form-row">
        <div class="col">
          <label for="friend_gifts_attributes_TEMPLATE_RECORD_name" class="form-label">Name</label>
          <input type="text" name="friend[gifts_attributes][TEMPLATE_RECORD][name]" id="friend_gifts_attributes_TEMPLATE_RECORD_name" class="form-control">
        </div>
        <div class="col">
          <label for="friend_gifts_attributes_TEMPLATE_RECORD_price" class="form-label">Price</label>
          <input type="text" name="friend[gifts_attributes][TEMPLATE_RECORD][price]" id="friend_gifts_attributes_TEMPLATE_RECORD_price" class="form-control">
        </div>
        <div class="col">
          <label for="friend_gifts_attributes_TEMPLATE_RECORD_link" class="form-label">Link</label>
          <input type="text" name="friend[gifts_attributes][TEMPLATE_RECORD][link]" id="friend_gifts_attributes_TEMPLATE_RECORD_link" class="form-control">
        </div>
        <div class="col">
          <a href="#" class="btn btn-danger" data-action="click->gifts#removeGift">Remove</a>
          <input type="hidden" name="friend[gifts_attributes][TEMPLATE_RECORD][_destroy]" id="friend_gifts_attributes_TEMPLATE_RECORD__destroy">
        </div>
      </div>
    </div>
  </template>
<% end %>

app/views/gifts/_gift.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title"> Gift Name: <%= gift.name %></h2>
      <p><strong>Price:</strong> <%= number_to_currency(gift.price) %></p>
      <% if gift.link.present? %>
        <%= link_to 'Visit Link', gift.link, target: '_blank', class: 'btn btn-link' %>
      <% end %>

      <div class="mt-4">
        <%= link_to 'Edit', edit_friend_gift_path(gift.friend, gift), class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/gifts/edit.html.erb
<h1>Editing gift</h1>

<%= render "form", friend: @friend, gift: @gift %>

<br>

<div>
  <%= link_to "Show this gift", friend_gift_path(@friend, @gift) %> |
  <%= link_to "Back to gifts", friend_path(@friend) %>
</div>

app/views/gifts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gifts</h1>

<div id="gifts">
  <% @gifts.each do |gift| %>
    <%= render gift %>
    <p>
      <%= link_to "Show this gift", gift %>
    </p>
  <% end %>
</div>

<%= link_to "New gift", new_gift_path %>

app/views/gifts/new.html.erb
<h1>New gift</h1>

<%= render "form", gift: @gift %>

<br>

<div>
  <%= link_to "Back to gifts", friend_gifts_path(@friend) %>
</div>

app/views/gifts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: 'gifts/gift', locals: { gift: @gift } %>

<br>
<div>
  <%= link_to "Edit this gift", edit_friend_gift_path(@gift.friend, @gift), class: 'btn btn-secondary' %>


  <%= button_to "Destroy this gift", friend_gift_path(@gift.friend, @gift),
                method: :delete,
                class: 'btn btn-danger',
                data: { confirm: 'Are you sure you want to delete this gift?' } %>

  <div id="alerts"></div>

  <div id="main">
    <%= yield %>
  </div>

</div>
<%= turbo_stream_from @friend %>

app/views/gifts/turbo_stream.erb
<% if @gift.destroyed? %>
  <%= turbo_stream.remove dom_id(@gift) %>
  <%= turbo_stream.prepend "alerts", partial: "shared/alert", locals: { message: "Gift successfully deleted", alert_type: "success" } %>
<% elsif @gift.errors.any? %>
  <%= turbo_stream.replace "new_gift_form", partial: "gifts/form", locals: { gift: @gift, friend: @friend } %>
<% elsif @gift.previous_changes.key?("id") %>
  <%= turbo_stream.append "gifts_list", partial: "gifts/gift", locals: { gift: @gift } %>
  <%= turbo_stream.replace "new_gift_form", partial: "gifts/form", locals: { gift: @friend.gifts.build, friend: @friend } %>
<% else %>
  <%= turbo_stream.replace dom_id(@gift), partial: "gifts/gift", locals: { gift: @gift } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsGifts</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
  <!-- Navigation Bar -->
  <%= render 'friends/nav_bar' %>

  <!-- Main Content -->
  <div class="container">
    <br/>
    <br/>
    <%= yield %>
  </div>

  <!-- Bootstrap JS and dependencies (optional) -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybBY5l5b6B9pWWLUbNMRPh34JfCGxQsPUsdbFRp3rIHlyzwt" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-ZP+QoGJRxdO0Qn5pdDeEQfHr6o3J2Fo5aP/EO3rGxlmszB4B8LMC8cpE02XqNfIw" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_alert.html.erb
<div class="alert alert-<%= alert_type %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>